spring:
  application:
    name: calvin-chess-tournament

engine:
  version: '@project.version@'

server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}

tournament:
  game-limit: 100
  move-limit: 100
  min-think-time-ms: 400
  max-think-time-ms: 700
  player-one:
    version: 1.8.0-AvoidRepetitions
    url: http://localhost:8080/calvin/game
  player-two:
    version: 1.9.0-LegalMoveGeneration
    url: http://localhost:8084/calvin/game