spring:
  application:
    name: calvin-chess-tournament

engine:
  version: '@project.version@'

server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}

tournament:
  game-limit: 100
  move-limit: 100
  min-think-time-ms: 500
  max-think-time-ms: 1500
  player-one:
    version: 1.0.0-InitialEngine
    url: http://localhost:8081/calvin/game
  player-two:
    version: 1.1.0-IterativeDeepening
    url: http://localhost:8080/calvin/game