spring:
  application:
    name: calvin-chess-tournament

engine:
  version: '@project.version@'

server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}

tournament:
  player-one:
    version: 1.0.0-InitialEngine
    url: http://localhost:8081/calvin/game
  player-two:
    version: 1.1.0-SNAPSHOT
    url: http://localhost:8081/calvin/game